### ISSUE TITLE
Background Image not working for HL

### ISSUE THREAD

**Issue by sheepsy90** [bhuman/GameController#21]
When starting the application the HL Leagues cannot start a game due to the new background color definitions being global in the GameController

**Comment by sheepsy90robocup** [comment]
This should be closed on merge of #22

**Comment by roefer** [comment]
The bug should be fixed now.

**Comment by sheepsy90robocup** [comment]
As soon as I am done with refactoring the Start Screen - I let you know (the pull request includes this)
