### ISSUE TITLE
Error while setting up GameController on port: 3939

### ISSUE THREAD

**Issue by ploth** [bhuman/GameController#25]
Could not load the GameController.jar until I inserted ```127.0.0.1 exec``` in my ```/etc/hosts``` file.
Otherwise this [line](https://github.com/bhuman/GameController/blob/84b7b6e4a64e03b3af522bfa88cdaf87ac02d387/src/teamcomm/net/SPLStandardMessageReceiver.java#L44) fails.
Probably it's because the username and hostname aren't different?

![image](https://cloud.githubusercontent.com/assets/7986123/24874779/224cd606-1e26-11e7-9ef5-7e109e0163ef.png)

**Comment by bhuman** [comment]
It is expected that you are connected to a network when using the GameController. Otherwise, you would not be able to reach any robots.

**Comment by ploth** [comment]
Yes, of course I was connected to a network. That was the first thing I checked.

**Comment by bhuman** [comment]
Well, 
```
InetAddress.getLocalHost().getAddress()
```
is a standard call from the Java runtime library. The [https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getLocalHost()](documentation)  lists some reasons why this might fail.

**Comment by ploth** [comment]
Might be a network misconfiguration on my side since it throws ``UnknownHostException - if the local host name could not be resolved into an address.``
Just wanted to mention it in case you want improve the error message.

**Comment by bhuman** [comment]
There should not have been an error message at all, because this error should have been ignored. It is fixed now, at least here in the repository.
