### ISSUE TITLE
Penalty Shootout Playing State Missing

### ISSUE THREAD

**Issue by KirstenH** [bhuman/GameController#26]
I just downloaded the latest Game Controller from http://spl.robocup.org/wp-content/uploads/downloads/GameController2017.zip and it seems to be missing the playing state during penalty shootouts as shown in the screenshot attached.

![image](https://user-images.githubusercontent.com/6583200/28244253-c456bdd8-6a28-11e7-9cef-4317a74e6819.png)

**Comment by bhuman** [comment]
No, it does not. You first have to pick the two players that are performing the penalty shootout. Then, the play button will become available.

**Comment by KirstenH** [comment]
Thank you, that makes sense.
